### ISSUE TITLE
Help me solve this problem in VSCode

### ISSUE THREAD

**Issue by riz-spec** [samudradev/samudra#30]
![image](https://github.com/user-attachments/assets/36ceb28c-9c1f-4f8a-ae83-aee6f2f058ed)

**Comment by Thaza-Kun** [comment]
Not sure why ask here since this is not a vscode or git repository, you can find better help in the vscode repository: https://github.com/microsoft/vscode/issues

Otherwise, this stackoverflow question might help.
https://stackoverflow.com/questions/29971624/visual-studio-code-cannot-detect-installed-git
